'use strict';

const LANGS = [ // 言語リスト
    { lang: 'ja', language: '日本語' },
    { lang: 'en', language: 'English' },
    // { lang: 'zh-TW', language: '繁體中文' },
    // { lang: 'zh-CH', language: '简体中文' },
    // { lang: 'ko', language: '한국어' },
    // { lang: 'fr', language: 'français' },
    // { lang: 'de', language: 'Deutsch' },
]

// 中文のコードは繁体＝zh-cmn-Hant・簡体＝zh-cmn-Hansが正しい？
// しかしGoogleのサイトはzh-TW・zh-CHとなっている。


// ここは未定義の言葉があれば分かりやすくエラーを返すように関数にした
const DICT = { // 翻訳辞書
    // タイトル（タイトルのキーを変更する場合はcommon.jsのlanguageも変更すること）
    'タイトル': {
        'ja': 'もぶぺったん',
        'en': 'Mob Stamp',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },

    // 拡張一覧
    '新生エオルゼア': {
        'ja': '新生エオルゼア',
        'en': 'A Realm Reborn',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '新生': {
        'ja': '新生',
        'en': 'A Realm Reborn',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '蒼天のイシュガルド': {
        'ja': '蒼天のイシュガルド',
        'en': 'Heavensward',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '蒼天': {
        'ja': '蒼天',
        'en': 'Heavensward',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '紅蓮のリベレーター': {
        'ja': '紅蓮のリベレーター',
        'en': 'Stormblood',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '紅蓮': {
        'ja': '紅蓮',
        'en': 'Stormblood',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '漆黒のヴィランズ': {
        'ja': '漆黒のヴィランズ',
        'en': 'Shadowbringers',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '漆黒': {
        'ja': '漆黒',
        'en': 'Shadowbringers',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '暁月のフィナーレ': {
        'ja': '暁月のフィナーレ',
        'en': 'Endwalker',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '暁月': {
        'ja': '暁月',
        'en': 'Endwalker',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '黄金のレガシー': {
        'ja': '黄金のレガシー',
        'en': 'Dawntrail',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '黄金': {
        'ja': '黄金',
        'en': 'Dawntrail',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },

    // 難易度
    '初級': {
        'ja': '初級',
        'en': 'Beginner',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '中級': {
        'ja': '中級',
        'en': 'Intermediate',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '上級': {
        'ja': '上級',
        'en': 'Advanced',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },

    // 暁月エリア
    'サベネア島': {
        'ja': 'サベネア島',
        'en': 'Thavnair',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ガレマルド': {
        'ja': 'ガレマルド',
        'en': 'Garlemald',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ラヴィリンソス': {
        'ja': 'ラヴィリンソス',
        'en': 'Labyrinthos',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '嘆きの海': {
        'ja': '嘆きの海',
        'en': 'Mare Lamentorum',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウルティマ・トゥーレ': {
        'ja': 'ウルティマ・トゥーレ',
        'en': 'Ultima Thule',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'エルピス': {
        'ja': 'エルピス',
        'en': 'Elpis',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },

    // 暁月エリア
    'カリブー': {
        'ja': 'カリブー',
        'en': 'Caribou',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ゲノーモス': {
        'ja': 'ゲノーモス',
        'en': 'Genomos',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トロル': {
        'ja': 'トロル',
        'en': 'Troll',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ノーザン・スナップウィード': {
        'ja': 'ノーザン・スナップウィード',
        'en': 'Northern Snapweed',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ペプレド': {
        'ja': 'ペプレド',
        'en': 'Pephredo',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'マウンテンチキン': {
        'ja': 'マウンテンチキン',
        'en': 'Luncheon Toad',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ミスリルキャップ': {
        'ja': 'ミスリルキャップ',
        'en': 'Mythrilcap',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ヤーコウ': {
        'ja': 'ヤーコウ',
        'en': 'Yakow',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ラヴィリンソス・スクリーマー': {
        'ja': 'ラヴィリンソス・スクリーマー',
        'en': 'Labyrinth Screamer',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'リマスカブラ': {
        'ja': 'リマスカブラ',
        'en': 'Limascabra',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アキャーリクラブ': {
        'ja': 'アキャーリクラブ',
        'en': 'Akyaali Crab',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アシュヴァッタ': {
        'ja': 'アシュヴァッタ',
        'en': 'Asvattha',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ヴァジュララングラ': {
        'ja': 'ヴァジュララングラ',
        'en': 'Vajralangula',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ヴァルラス': {
        'ja': 'ヴァルラス',
        'en': 'Valras',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オドカン': {
        'ja': 'オドカン',
        'en': 'Odqan',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ガジャ': {
        'ja': 'ガジャ',
        'en': 'Gaja',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'カチャパ': {
        'ja': 'カチャパ',
        'en': 'Kacchapa',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'グハーシャヤ': {
        'ja': 'グハーシャヤ',
        'en': 'Guhasaya',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'サベネアンジャムメル': {
        'ja': 'サベネアンジャムメル',
        'en': 'Thavnairian Jhammel',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'シュトラムルグ': {
        'ja': 'シュトラムルグ',
        'en': 'Sotormurg',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'スターマイト': {
        'ja': 'スターマイト',
        'en': 'Starmite',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'チャムロッシュ': {
        'ja': 'チャムロッシュ',
        'en': 'Chamrosh',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'バブーン': {
        'ja': 'バブーン',
        'en': 'Ufiti',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ハンサ': {
        'ja': 'ハンサ',
        'en': 'Hamsa',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ピシャーチャ': {
        'ja': 'ピシャーチャ',
        'en': 'Pisaca',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブンジャンガ': {
        'ja': 'ブンジャンガ',
        'en': 'Bhujamga',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'マンジュサカ': {
        'ja': 'マンジュサカ',
        'en': 'Manjusaka',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アルマスティ': {
        'ja': 'アルマスティ',
        'en': 'Almasty',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'イルサバード・トゥルスス': {
        'ja': 'イルサバード・トゥルスス',
        'en': 'Ilsabardian Tursus',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'エブラーナ・アイストラップ': {
        'ja': 'エブラーナ・アイストラップ',
        'en': 'Eblan Icetrap',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'エブラーナベアー': {
        'ja': 'エブラーナベアー',
        'en': 'Eblan Bear',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オートマチック・アヴェンジャー': {
        'ja': 'オートマチック・アヴェンジャー',
        'en': 'Automated Avenger',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オートマチック・キャバルリー': {
        'ja': 'オートマチック・キャバルリー',
        'en': 'Automated Cavalry',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オートマチック・コロッサス': {
        'ja': 'オートマチック・コロッサス',
        'en': 'Automated Colossus',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オートマチック・サテライト': {
        'ja': 'オートマチック・サテライト',
        'en': 'Automated Satellite',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オートマチック・スラッシャー': {
        'ja': 'オートマチック・スラッシャー',
        'en': 'Automated Slasher',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オートマチック・デスマシーン': {
        'ja': 'オートマチック・デスマシーン',
        'en': 'Automated Death Machine',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オートマチック・ビット': {
        'ja': 'オートマチック・ビット',
        'en': 'Automated Bit',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オートマチック・マグナローダー': {
        'ja': 'オートマチック・マグナローダー',
        'en': 'Automated Roader',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オーバーグロウン・ローズ': {
        'ja': 'オーバーグロウン・ローズ',
        'en': 'Overgrown Rose',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オウヴィボス': {
        'ja': 'オウヴィボス',
        'en': 'Ovibos',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'カニスルピナス': {
        'ja': 'カニスルピナス',
        'en': 'Canis Lupinus',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'セルリウムゾブラン': {
        'ja': 'セルリウムゾブラン',
        'en': 'Ceruleum Zoblyn',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ヨトゥン': {
        'ja': 'ヨトゥン',
        'en': 'Jotunn',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アーマルコライト': {
        'ja': 'アーマルコライト',
        'en': 'Armalcolite',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウィーパー': {
        'ja': 'ウィーパー',
        'en': 'Weeper',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オスキュレーター': {
        'ja': 'オスキュレーター',
        'en': 'Osculator',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ケアテイカー': {
        'ja': 'ケアテイカー',
        'en': 'Caretaker',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'サポーター': {
        'ja': 'サポーター',
        'en': 'Supporter',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'シンカー': {
        'ja': 'シンカー',
        'en': 'Thinker',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'スウィーパー': {
        'ja': 'スウィーパー',
        'en': 'Sweeper',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'スクレーパー': {
        'ja': 'スクレーパー',
        'en': 'Scraper',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ダイナマイト': {
        'ja': 'ダイナマイト',
        'en': 'Dynamite',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ダウンフォール・アラーム': {
        'ja': 'ダウンフォール・アラーム',
        'en': 'Downfall Alarum',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ダウンフォール・ドロイド': {
        'ja': 'ダウンフォール・ドロイド',
        'en': 'Downfall Droid',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ダウンフォール・ハンター': {
        'ja': 'ダウンフォール・ハンター',
        'en': 'Downfall Hunter',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ダフニア': {
        'ja': 'ダフニア',
        'en': 'Daphnia',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トリマー': {
        'ja': 'トリマー',
        'en': 'Trimmer',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'パノプト': {
        'ja': 'パノプト',
        'en': 'Panopt',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ムース': {
        'ja': 'ムース',
        'en': 'Mousse',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'レゴリス': {
        'ja': 'レゴリス',
        'en': 'Regolith',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ワンダラー': {
        'ja': 'ワンダラー',
        'en': 'Wanderer',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アカンサ': {
        'ja': 'アカンサ',
        'en': 'Akantha',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'イグドリア': {
        'ja': 'イグドリア',
        'en': 'Yggdreant',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'エルピスタウロス': {
        'ja': 'エルピスタウロス',
        'en': 'Elpis Minotaur',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オキュペテ': {
        'ja': 'オキュペテ',
        'en': 'Okyupete',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オピオタウロス': {
        'ja': 'オピオタウロス',
        'en': 'Ophiotauros',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オピオン': {
        'ja': 'オピオン',
        'en': 'Ophion',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'グリュプス': {
        'ja': 'グリュプス',
        'en': 'Gryps',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'バード・オブ・エルピス': {
        'ja': 'バード・オブ・エルピス',
        'en': 'Bird of Elpis',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ハルピュイア': {
        'ja': 'ハルピュイア',
        'en': 'Harpuia',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ヒッペー': {
        'ja': 'ヒッペー',
        'en': 'Hippe',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ファノプシュケ': {
        'ja': 'ファノプシュケ',
        'en': 'Phanopsyche',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ペガソス': {
        'ja': 'ペガソス',
        'en': 'Pegasos',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'マーカス・モルボル': {
        'ja': 'マーカス・モルボル',
        'en': 'Morbol Marquis',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'メラニオン': {
        'ja': 'メラニオン',
        'en': 'Melanion',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'モノセロス': {
        'ja': 'モノセロス',
        'en': 'Monoceros',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'リコペルシクム': {
        'ja': 'リコペルシクム',
        'en': 'Lykopersikon',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'レモラ': {
        'ja': 'レモラ',
        'en': 'Remora',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ロティス': {
        'ja': 'ロティス',
        'en': 'Lotis',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アザーワン': {
        'ja': 'アザーワン',
        'en': 'Other One',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ステラ・アンフィプテレ': {
        'ja': 'ステラ・アンフィプテレ',
        'en': 'Stellar Amphiptere',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ステラ・ブロビニャク': {
        'ja': 'ステラ・ブロビニャク',
        'en': 'Stellar Brobinyak',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'デルタ': {
        'ja': 'デルタ',
        'en': 'Delta',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ドリフティング・イーア': {
        'ja': 'ドリフティング・イーア',
        'en': 'Drifting Ea',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブロークン・オミクロン': {
        'ja': 'ブロークン・オミクロン',
        'en': 'Broken Omicron',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ベータ': {
        'ja': 'ベータ',
        'en': 'Beta',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ラムダ': {
        'ja': 'ラムダ',
        'en': 'Lambda',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'レベルトリッカー': {
        'ja': 'レベルトリッカー',
        'en': 'Level Tricker',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    // 黄金エリア
    'オルコ・パチャ': {
        'ja': 'オルコ・パチャ',
        'en': 'Urqopacha',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'コザマル・カ': {
        'ja': 'コザマル・カ',
        'en': 'Kozama\'uka',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ヤクテル樹海': {
        'ja': 'ヤクテル樹海',
        'en': 'Yak T\'el',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'シャーローニ荒野': {
        'ja': 'シャーローニ荒野',
        'en': 'Shaaloani',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ヘリテージファウンド': {
        'ja': 'ヘリテージファウンド',
        'en': 'Heritage Found',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'リビング・メモリー': {
        'ja': 'リビング・メモリー',
        'en': 'Living Memory',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },

    // モンスター

    'チャバ・ガーダン': {
        'ja': 'チャバ・ガーダン',
        'en': 'Chaba Gedan',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アルパカ': {
        'ja': 'アルパカ',
        'en': 'Alpaca',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トラルラーテル': {
        'ja': 'トラルラーテル',
        'en': 'Turali Ratel',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'シルバリオ': {
        'ja': 'シルバリオ',
        'en': 'Silver Lobo',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'シエナム': {
        'ja': 'シエナム',
        'en': 'Siehnam',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トラチュー': {
        'ja': 'トラチュー',
        'en': 'Tulichu',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'バンデルクァール': {
        'ja': 'バンデルクァール',
        'en': 'Bandercoeurl',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'メガマゲイ': {
        'ja': 'メガマゲイ',
        'en': 'Megamaguey',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'スパインモール': {
        'ja': 'スパインモール',
        'en': 'Barbmole',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'マウンテンベアー': {
        'ja': 'マウンテンベアー',
        'en': 'Mountain Bear',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ノトカクター': {
        'ja': 'ノトカクター',
        'en': 'Notocactuar',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブラッドサッカー': {
        'ja': 'ブラッドサッカー',
        'en': 'Bloodsucker',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'モルテン・フォーバッド': {
        'ja': 'モルテン・フォーバッド',
        'en': 'Molten Phoebad',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トラルダイル': {
        'ja': 'トラルダイル',
        'en': 'Tulidile',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ナーヨードー': {
        'ja': 'ナーヨードー',
        'en': 'Naryordor',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ビッグジョウ': {
        'ja': 'ビッグジョウ',
        'en': 'Longjaw',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'チーワグー・サベラー': {
        'ja': 'チーワグー・サベラー',
        'en': 'Chirwagur Sabreur',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'フリント': {
        'ja': 'フリント',
        'en': 'Flint',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ワジェペン': {
        'ja': 'ワジェペン',
        'en': 'Huallepen',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'リッジトラップ': {
        'ja': 'リッジトラップ',
        'en': 'Ridgetrap',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウォロン': {
        'ja': 'ウォロン',
        'en': 'Uolon',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ジャングルペリカン': {
        'ja': 'ジャングルペリカン',
        'en': 'Jungle Pelican',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ヘヴィ・マタマタ': {
        'ja': 'ヘヴィ・マタマタ',
        'en': 'Heavy Matamata',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トゥカリブリ': {
        'ja': 'トゥカリブリ',
        'en': 'Toucalibri',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ライノビートル': {
        'ja': 'ライノビートル',
        'en': 'Rhino Beetle',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ハンマーヘッドダイル': {
        'ja': 'ハンマーヘッドダイル',
        'en': 'Hammerhead Crocodile',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ジャングルオロボン': {
        'ja': 'ジャングルオロボン',
        'en': 'Jungle Orobon',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'グロウフライ': {
        'ja': 'グロウフライ',
        'en': 'Glowfly',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'レッサーアポリオン': {
        'ja': 'レッサーアポリオン',
        'en': 'Lesser Apollyon',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ジャングルイグアナ': {
        'ja': 'ジャングルイグアナ',
        'en': 'Jungle Iguana',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トラルネツァク': {
        'ja': 'トラルネツァク',
        'en': 'Turali Netzach',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トマトン': {
        'ja': 'トマトン',
        'en': 'Tomaton',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'バード・オブ・リガカ': {
        'ja': 'バード・オブ・リガカ',
        'en': 'Bird of Ligaka',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'スワンプモンク': {
        'ja': 'スワンプモンク',
        'en': 'Swampmonk',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トラルモルボル': {
        'ja': 'トラルモルボル',
        'en': 'Turali Morbol',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウィドウメイカー': {
        'ja': 'ウィドウメイカー',
        'en': 'Widowmaker',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'テグー': {
        'ja': 'テグー',
        'en': 'Tegu',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ペーパーワスプ': {
        'ja': 'ペーパーワスプ',
        'en': 'Paper Wasp',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウォツ': {
        'ja': 'ウォツ',
        'en': 'U\'out',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ポイズンフロッグ': {
        'ja': 'ポイズンフロッグ',
        'en': 'Poison Frog',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'オセロット': {
        'ja': 'オセロット',
        'en': 'Ocelot',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウッドマン': {
        'ja': 'ウッドマン',
        'en': 'Woodsman',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'スティンクシェル': {
        'ja': 'スティンクシェル',
        'en': 'Stinkshell',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ヴァザラル・ブラーシャ': {
        'ja': 'ヴァザラル・ブラーシャ',
        'en': 'Vawtsaral Br\'aax',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'イブルク': {
        'ja': 'イブルク',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'リーフマンティス': {
        'ja': 'リーフマンティス',
        'en': 'Leaf Mantis',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ネクローシス': {
        'ja': 'ネクローシス',
        'en': 'Necrosis',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'チャイチャ': {
        'ja': 'チャイチャ',
        'en': 'Ty\'aitya',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'バードロ': {
        'ja': 'バードロ',
        'en': 'Balyaborr',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'キラーピラニア': {
        'ja': 'キラーピラニア',
        'en': 'Killer Piranha',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ヤクテル・スクイブ': {
        'ja': 'ヤクテル・スクイブ',
        'en': 'Yak T\'el squib',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トォーソク': {
        'ja': 'トォーソク',
        'en': 'T\'ohsoq',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トォーゾン': {
        'ja': 'トォーゾン',
        'en': 'T\'ohts\'on',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ピッチャーウィード': {
        'ja': 'ピッチャーウィード',
        'en': 'Pitcher Weed',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'モーナー': {
        'ja': 'モーナー',
        'en': 'Mourner',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アンテサンサン': {
        'ja': 'アンテサンサン',
        'en': 'Sarracenia',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ジャティーカモス': {
        'ja': 'ジャティーカモス',
        'en': 'Ja Tiika Moth',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブランチベアラー': {
        'ja': 'ブランチベアラー',
        'en': 'Branchbearer',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'フライアガリク': {
        'ja': 'フライアガリク',
        'en': 'Fly Agaric',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブルーモルフォ': {
        'ja': 'ブルーモルフォ',
        'en': 'Blue Morpho',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブルーリフキン': {
        'ja': 'ブルーリフキン',
        'en': 'Blue Leafkin',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'タンブルクラブ': {
        'ja': 'タンブルクラブ',
        'en': 'Tumbleclaw',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'サンビアード': {
        'ja': 'サンビアード',
        'en': 'Sunbeard',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'フライングポポト': {
        'ja': 'フライングポポト',
        'en': 'Flying Popoto',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'グラスランドウォーム': {
        'ja': 'グラスランドウォーム',
        'en': 'Grasslands Worm',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ノパルテンダー': {
        'ja': 'ノパルテンダー',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ルニュカワッパ': {
        'ja': 'ルニュカワッパ',
        'en': 'Lunyucaua\'pya',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ルニュヒーシャヘ': {
        'ja': 'ルニュヒーシャヘ',
        'en': 'Lunyuhiyshahe',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'エヘヘケヤー': {
        'ja': 'エヘヘケヤー',
        'en': 'Yeheheceyaa',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'キャニオンバット': {
        'ja': 'キャニオンバット',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ワイルドダラ': {
        'ja': 'ワイルドダラ',
        'en': 'Wild Dhara',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'セルリックボム': {
        'ja': 'セルリックボム',
        'en': 'Cerule Bomb',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'セルリックアナラ': {
        'ja': 'セルリックアナラ',
        'en': 'Cerule Anala',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ホーンリザード': {
        'ja': 'ホーンリザード',
        'en': 'Horned Lizard',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アスピス': {
        'ja': 'アスピス',
        'en': 'Aspis',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'マチュア・ノパルテンダー': {
        'ja': 'マチュア・ノパルテンダー',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ロネーク': {
        'ja': 'ロネーク',
        'en': 'Rroneek',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'グリットクロウ': {
        'ja': 'グリットクロウ',
        'en': 'Gritclaw',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ケラトラプトル': {
        'ja': 'ケラトラプトル',
        'en': 'Ceratoraptor',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トラルタイマイ': {
        'ja': 'トラルタイマイ',
        'en': 'Turali Hawksbill',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トーリ・アリゲーター': {
        'ja': 'トーリ・アリゲーター',
        'en': 'Toari Alligator',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブロークン・タレット': {
        'ja': 'ブロークン・タレット',
        'en': 'Defective Turret',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アックスビーク': {
        'ja': 'アックスビーク',
        'en': 'Axe Beak',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'カワヘアロー': {
        'ja': 'カワヘアロー',
        'en': 'Cauahealoa',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'カワヘパ': {
        'ja': 'カワヘパ',
        'en': 'Cauahepya',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ミリメロン': {
        'ja': 'ミリメロン',
        'en': 'Myrmeleon',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'エーニシェーニ・バット': {
        'ja': 'エーニシェーニ・バット',
        'en': 'Yyenisheyni Bat',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'カトブレプタ': {
        'ja': 'カトブレプタ',
        'en': 'Katobleps',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'サンダースピリット': {
        'ja': 'サンダースピリット',
        'en': 'Thunder Spirit',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ボルトハウンド': {
        'ja': 'ボルトハウンド',
        'en': 'Bolt Hound',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブロークン・セントリーS8': {
        'ja': 'ブロークン・セントリーS8',
        'en': 'Defective Sentry S8',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アステロディア': {
        'ja': 'アステロディア',
        'en': 'Asterodia',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ゴンフォテリウム': {
        'ja': 'ゴンフォテリウム',
        'en': 'Gomphotherium',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブロークン・エアロスタット': {
        'ja': 'ブロークン・エアロスタット',
        'en': 'Defective Aerostat',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブロークン・セントリーR8': {
        'ja': 'ブロークン・セントリーR8',
        'en': 'Defective Sentry R8',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アイクロプス': {
        'ja': 'アイクロプス',
        'en': 'Eyeclops',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウールバック': {
        'ja': 'ウールバック',
        'en': 'Woolback',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'パイソン': {
        'ja': 'パイソン',
        'en': 'Python',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'グリーンマン': {
        'ja': 'グリーンマン',
        'en': 'Timberman',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウィンドスプライト': {
        'ja': 'ウィンドスプライト',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アウトランナー': {
        'ja': 'アウトランナー',
        'en': 'Outrunner',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アガヴォイデス': {
        'ja': 'アガヴォイデス',
        'en': 'Agavoides',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ユー': {
        'ja': 'ユー',
        'en': 'Everlasting Yew',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウォーキングツリー': {
        'ja': 'ウォーキングツリー',
        'en': 'Walking Tree',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウィンドスピリット': {
        'ja': 'ウィンドスピリット',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウォータースプライト': {
        'ja': 'ウォータースプライト',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'トルバラン': {
        'ja': 'トルバラン',
        'en': 'Torbalan',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'メモリーバード': {
        'ja': 'メモリーバード',
        'en': 'Remembird',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'フルイドソウル': {
        'ja': 'フルイドソウル',
        'en': 'Fluid Soul',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ウォータースピリット': {
        'ja': 'ウォータースピリット',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アーススプライト': {
        'ja': 'アーススプライト',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'シーカーバット': {
        'ja': 'シーカーバット',
        'en': 'Seeker Bat',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ジェムキーパー': {
        'ja': 'ジェムキーパー',
        'en': 'Gemkeeper',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'フライングキャット': {
        'ja': 'フライングキャット',
        'en': 'Acrocat',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ブラウニー': {
        'ja': 'ブラウニー',
        'en': 'Brownie',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ファイアスプライト': {
        'ja': 'ファイアスプライト',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ガルガンチュア': {
        'ja': 'ガルガンチュア',
        'en': 'Gargantua',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'アサルトシザー': {
        'ja': 'アサルトシザー',
        'en': 'Alexandrian Clipper',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'ファイアソウル': {
        'ja': 'ファイアソウル',
        'en': 'Blazing Soul',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'パイナップル': {
        'ja': 'パイナップル',
        'en': 'Pineapple',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'マッチロック・スコーピオン': {
        'ja': 'マッチロック・スコーピオン',
        'en': 'Matchlock Scorpion',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },

    // 手配書
    '手配書': {
        'ja': '手配書',
        'en': 'Wanted Poster',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '手配書のモンスターを選ぶ': {
        'ja': '　手配書のモンスターを選ぶ（1・2匹目のみ表記）',
        'en': 'Check your target on Wanted Poster. The first and second targets are displayed.',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '複数選択可': {
        'ja': '複数選択可にする',
        'en': 'Enable multiple select.',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'リセット': {
        'ja': 'リセット',
        'en': 'Reset',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },

    // 地図
    '地図': {
        'ja': '地図',
        'en': 'Hunting Map',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    'エリア順': {
        'ja': 'エリア順',
        'en': 'ByArea',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '拡張順': {
        'ja': '拡張順',
        'en': 'ByExpansion',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '極小': {
        'ja': '極小',
        'en': 'VerySmall',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '小': {
        'ja': ' 小 ',
        'en': 'Small',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '中': {
        'ja': ' 中 ',
        'en': 'Medium',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '大': {
        'ja': ' 大 ',
        'en': 'Large',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    '極大': {
        'ja': '極大',
        'en': 'VeryLarge',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },






/*
    '': {
        'ja': '',
        'en': '',
        'zh-TW': '',
        'zh-CH': '',
        'ko': '',
        'fr': '',
        'de': '',
    },
    */
}
const WORD = msg => { // 辞書変換
    if (DICT[msg]) {
        return DICT[msg];
    } else {
        let errorMsg = {
            'ja': msg,
            'en': msg,
            'zh-TW': msg,
            'zh-CH': msg,
            'ko': msg,
            'fr': msg,
            'de': msg,
        }
        log('WORD: ' + msg + ' は未定義');
        return errorMsg;
    }
}
