'use strict';

const TKOOL = 'https://helfard.github.io/ffxiv/stkool/'; // 潜水艦ツクールのURL

const AREA = [
  {
    id: 'A',
    name: '祭壇島',
    move: 7,
    sink: 22,
    smove: [0, 32, 12, 32, 26, 33, 23, 23],
    x: 50,
    y: 133,
    kyori: 8624,
    research: 61600,
    distance: [0, 37295, 13902, 37495, 30112, 38636, 26493, 27095],
    drop: [
      { name: 'アロハウソウソ', tansa: 190 },
    ],
    luck: 175,
  }, {
    id: 'B',
    name: '蛸壺入江',
    move: 35,
    sink: 22,
    smove: [32, 0, 25, 18, 25, 21, 28, 33],
    x: 65,
    y: 217,
    kyori: 40800,
    research: 61600,
    distance: [37295, 0, 29092, 20770, 28744, 24172, 32136, 38643],
    drop: [
      { name: '巨像の欠片', tansa: 190 },
    ],
    luck: 175,
  }, {
    id: 'C',
    name: '翠浪海01',
    move: 18,
    sink: 22,
    smove: [12, 25, 0, 21, 14, 22, 15, 16],
    x: 70,
    y: 77,
    kyori: 21486,
    research: 61600,
    distance: [61599, 29092, 0, 25012, 16708, 25192, 17595, 18612],
    drop: [
      { name: '舞海月', tansa: 190 },
    ],
    luck: 175,
  }, {
    id: 'D',
    name: 'ロゴトゥムヘレの狩場',
    move: 37,
    sink: 23,
    smove: [32, 18, 21, 0, 17, 5, 27, 29],
    x: 15,
    y: 49,
    kyori: 42822,
    research: 63000,
    distance: [37495, 20770, 25012, 0, 19632, 6154, 30861, 33543],
    drop: [
      { name: 'シマエナガ', tansa: 195 },
    ],
    luck: 180,
  }, {
    id: 'E',
    name: '吸盤礁',
    move: 33,
    sink: 23,
    smove: [26, 25, 14, 17, 0, 13, 11, 12],
    x: 141,
    y: 11,
    kyori: 38064,
    research: 63000,
    distance: [30112, 28744, 16708, 19632, 0, 15843, 13419, 14439],
    drop: [
      { name: 'ミーアキャット', tansa: 195 },
    ],
    luck: 185,
  }, {
    id: 'F',
    name: 'ロゴトゥムヘレの寝蔵',
    move: 39,
    sink: 24,
    smove: [33, 21, 22, 5, 13, 0, 24, 26],
    x: 55,
    y: 14,
    kyori: 44886,
    research: 64400,
    distance: [38635, 24171, 25191, 6153, 15873, 0, 28203, 30225],
    drop: [
      { name: '紫漆塗番傘', tansa: 195 },
    ],
    luck: 185,
  }, {
    id: 'G',
    name: 'タナロアの釣針',
    move: 30,
    sink: 24,
    smove: [23, 28, 15, 27, 11, 24, 0, 7],
    x: 213,
    y: 67,
    kyori: 34666,
    research: 65100,
    distance: [26490, 32135, 17595, 30860, 13415, 28300, 0, 8125],
    drop: [
      { name: 'オーケストリオン譜：宿命', tansa: 195 },
    ],
    luck: 0,
  }, {
    id: 'H',
    name: '翠浪海02',
    move: 31,
    sink: 25,
    smove: [23, 33, 16, 29, 12, 26, 7, 0],
    x: 207,
    y: 9,
    kyori: 35682,
    research: 65800,
    distance: [27095, 38640, 18610, 33540, 14435, 30225, 8125, 0],
    drop: [
      { name: '結晶掘りの鞄', tansa: 195 },
    ],
    luck: 185,
    /*
  }, {
  id: 'I',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'J',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'K',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'L',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'M',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'N',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'O',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'P',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'Q',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'R',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'S',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'T',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'U',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'V',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'W',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'X',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'Y',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
  }, {
  id: 'Z',
  name: '',
  move: ,
  sink: ,
  smove: [],
  x: ,
  y: ,
  kyori: ,
  research: ,
  distance: [],
  drop: [
    { name: '', tansa: },
    { name: '', tansa: },
    { name: '', tansa: },
  ],
  luck: 0,
*/
  }
];

const ITEMS = [
  // 逆引き用のリスト
  'ココボロ材',
  'ピュアチタン鉱',
  'クリプトメリア原木',
  'アロハウソウソ',
  '巨像の欠片',
  '舞海月',
  'シマエナガ',
  'ミーアキャット',
  '紫漆塗番傘',
  'オーケストリオン譜：宿命',
  '結晶掘りの鞄',
];